#
# Site settings
#
title:			sir-he blog
email:			h525619010@sina.com
description: "开源改变世界,为开源献上力量,专注web领域研究与分享"
keywords: "sir-he,sir-he blog,sir-he.github.io,何先生的博客,何先森的博客,开源改变世界,为开源献上力量,专注web领域研究与分享"
url: "https://sir-he.github.io"
baseurl:		""
# twitter_username:	sir-he
github_username:	sir-he

#
# Build settings
#
markdown:		kramdown
# to show future post, run 'jekyll serve --future'
future:			false

#
# Pagination config
#
gems:			[jekyll-paginate]
paginate:		15
paginate_path:		"/page:num/"


#
# Other settings
#
excerpt_separator:	<!--more-->
